In [4]:
#importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
#importing dataset
dataset=pd.read_csv('D:\\DD\\Users\\50_Startups.csv')

In [8]:
#first 10 values
dataset.head(10)

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94
5  131876.90        99814.71        362861.36  156991.12
6  134615.46       147198.87        127716.82  156122.51
7  130298.13       145530.06        323876.68  155752.60
8  120542.52       148718.95        311613.29  152211.77
9  123334.88       108679.17        304981.62  149759.96

In [10]:
#checking for missing values
dataset.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

In [13]:
#dividing with depandent and independent variables
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [14]:
x

array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34,  91391.77, 366168.42],
       [131876.9 ,  99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [ 78013.11, 121597.55, 264346.06],
       [ 94657.16, 145077.58, 282574.31],
       [ 91749.16, 114175.79, 294919.57],
       [ 86419.7 , 153514.11,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78389.47, 153773.43, 299737.29],
       [ 73994.56, 122782.75, 303319.26],
       [ 67532.53, 105751.03, 3047

In [15]:
#Training and Testing the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
# Linear Model
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)

In [18]:
y_pred

array([103901.8969696 , 132763.05993126, 133567.90370044,  72911.78976736,
       179627.92567224, 115166.64864795,  67113.5769057 ,  98154.80686776,
       114756.11555221, 169064.01408795])

In [29]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=4)
x_poly=poly.fit_transform(x)
reg2=LinearRegression()
reg2.fit(x_poly,y)
x_poly

array([[1.00000000e+00, 1.65349200e+05, 1.36897800e+05, ...,
        4.17137792e+21, 1.43756129e+22, 4.95419619e+22],
       [1.00000000e+00, 1.62597700e+05, 1.51377590e+05, ...,
        4.51534135e+21, 1.32407537e+22, 3.88270887e+22],
       [1.00000000e+00, 1.53441510e+05, 1.01145550e+05, ...,
        1.70245060e+21, 6.86622794e+21, 2.76924841e+22],
       ...,
       [1.00000000e+00, 0.00000000e+00, 1.35426920e+05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 5.42050000e+02, 5.17431500e+04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 1.16983800e+05, ...,
        2.79261116e+19, 1.07836121e+19, 4.16407019e+18]])

In [30]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9393955917820572